DROP TABLE IF EXISTS PLAYER;

CREATE TABLE PLAYER (
  PLAYER_ID INT AUTO_INCREMENT  PRIMARY KEY,
  NAME VARCHAR(250) NOT NULL,
  COUNTRY VARCHAR(250) NOT NULL,
  POSITION INT NOT NULL,
  RATING INT DEFAULT NULL
);

INSERT INTO PLAYER(NAME, COUNTRY, POSITION, RATING) VALUES
('Virat Kohli', 'IN', 1, 871),
('Rohit Sharma', 'IN', 2, 855),
('Babar Azam', 'PK', 3, 837);
